name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '30 3 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: zisismaras/marlin_auto_build@master
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware-bin
        path: path/to/generated/firmware.bin
