name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '30 3 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: zisismaras/marlin_auto_build@master
    - name: Workaround for GitHub Token
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
